#ifndef __COMMON_HEADERS_H__
#define __COMMON_HEADERS_H__
typedef enum
{
    SYSTEM_OK,
    SYSTEM_NULL_PARAMETER,
    SYSTEM_INVALID_PARAMETER,
    SYSTEM_INVALID_PIN_NUMBER,
    SYSTEM_INVALID_STATE,
    SYSTEM_INVALID_MODE,
    SYSTEM_INVALID_BAUD_RATE,
    SYSTEM_INVALID_LENGTH,
    SYSTEM_TIMED_OUT,
    SYSTEM_BUFFER_OVERFLOW,
    SYSTEM_UNKNOWN,
    SYSTEM_FAILED,
    SYSTEM_INVALID_TEMPERATURE,
    SYSTEM_INVALID_PIN_PORT,
    SYSTEM_NO_RESPONSE,
    SYSTEM_NO_ACK,
    SYSTEM_CHECK_SUM_VALIDATION_FAILED,
    SYSTEM_BUSY,
    SYSTEM_OPERATION_FAILED,
    SYSTEM_INVALID_RESPONSE,
} error_type_t;
#endif // __COMMON_HEADERS_H__