openapi: '3.0.3'
info:
  title: API Title
  version: '1.0'
components:
  securitySchemes:
    cookieAuth: # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: SID # cookie name

servers:
  - url: http://fpc-webserver.local
    description: Local ESP32 Webserver
paths:
  /dummy:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: Dummy response

  /register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password1:
                  type: string
                password2:
                  type: string
      responses:
        '200':
          description: Registration successful
          content:
            text/plain:
              schema:
                type: string
              example: Registration successful
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
              example: Invalid input data

  /login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            text/plain:
              schema:
                type: string
              example: Login successful
          headers:
            Set-Cookie:
              schema:
                type: string
                example: SID=abcde12345; Path=/; HttpOnly; SameSite=Strict; Max-Age=3600
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                type: string
              example: Invalid credentials
  /logout:
    post:
      security:
        - cookieAuth: [] # Use the cookie authentication scheme
      responses:
        '200':
          description: Logout successful
          content:
            text/plain:
              schema:
                type: string
              example: Logout successful
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
              example: Invalid request
  /config:
    get:
      security:
        - cookieAuth: [] # Use the cookie authentication scheme
      responses:
        '200':
          description: Configuration retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  setting1:
                    type: string
                  setting2:
                    type: string
              example:
                setting1: value1
                setting2: value2
        '404':
          description: Configuration not found
          content:
            text/plain:
              schema:
                type: string
              example: Configuration not found
    post:
      security:
        - cookieAuth: [] # Use the cookie authentication scheme
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                setting1:
                  type: string
                setting2:
                  type: string
      responses:
        '200':
          description: Configuration updated successfully
          content:
            text/plain:
              schema:
                type: string
              example: Configuration updated successfully
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
              example: Invalid configuration data
  /reset:
    post:
      security:
        - cookieAuth: [] # Use the cookie authentication scheme
      responses:
        '200':
          description: Reset successful
          content:
            text/plain:
              schema:
                type: string
              example: Reset successful
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
              example: Failed to clear credential store